# Generated by Django 3.2.8 on 2021-10-19 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20211018_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patientname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.IntegerField(choices=[(1, 'Doctor'), (2, 'Patient')], default=1),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
